### ISSUE TITLE
Assets breaks site, exucute php code on home page reload

### ISSUE THREAD

**Issue by otahirs** [getgrav/grav-plugin-assets#7]
When you have a php code placed on any page using the `{{example()}}` [custom plugin](https://learn.getgrav.org/cookbook/plugin-recipes#output-some-php-code-result-in-a-twig-template), the php code is executed when the home page (and only home page) is reloaded.  
  
I was unable to replicate this issue with clear install  (grav+admin with only assets plugin installed), but I still consider it a major problem.

**Comment by otahirs** [comment]
Also the load time (TTFB) of the page was significantly improved after disabling the plugin.

**Comment by rhukster** [comment]
Not really following you on the issue here.  The "Twig" code you have above is placed where? inside a markdown file? or in a twig template?  If in a markdown file you would need to have serveral things set in that page's frontmatter:

```
process:
  twig: true
```

To enable twig processing for the page.

```
never_cache_twig: true
```

To ensure the result from the Twig is not cached, and is processed every time. or...

```
cache_enable: false
```

To disable the cache on the page entirely.

However, if your `{{ example() }}` is in a twig page template, it should run everytime no problem. 

The last part of the equation is where exactly is your `example()` method defined? This is a method, so i'm assuming you've defined a custom Twig 'function' in a plugin.  Is this always defined before it's used?  

Just so many variables here, and it's not clear what you are doing exactly.

**Comment by otahirs** [comment]
Normally when you load a page and there is a call for a custom twig function, the function gets called and the code executed.   
However, what I came across is, that when I reloaded a home page, then all the functions that are placed somewhere on the site in another pages (using twig in page content) are fired. I know it sounds a little bit strange. 

example:
I have custom twig function that alerts "hello world" using javascript allert, named `hello()`. I placed the call for this function in pages/php/defautl.md as `{{ hello() }}`.
When i reload page/home/default.md that is blank I get an "hello world" alert on the screen.

I didnt even used any functionality of this plugin anymore and was looking for the cause of this bug, when I dissabled the assets plugin, this odd behavior disapeared.
